[package]
name = "ladroncito"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "4.6.0"
csv = "1.4.0"
rayon = "1.11.0"
reqwest = { version ="0.13.2", features = ["json"] }
rocket = { version = "0.5.1", features = ["json"] }
rocket_ws = "0.1.1"
serde = { version = "1.0.228", features = ["derive"] }
serde_yaml = "0.9.34"
tokio = { version = "1.50.0", features = ["full"] }
uuid = { version = "1.23.0", features = ["v4", "serde"] }
